# $lock_cmd = hyprctl dispatch global quickshell:lock & pidof qs quickshell hyprlock || hyprlock
$lock_cmd = [[ -f ~/.inhib_idle ]] || pidof hyprlock || hyprlock
$screen_off = [[ -f ~/.inhib_idle ]] || hyprctl dispatch dpms off
$screen_on = [[ -f ~/.inhib_idle ]] || hyprctl dispatch dpms on && brightnessctl -r
$suspend_cmd = systemctl suspend || loginctl suspend

general {
    lock_cmd = $lock_cmd
    before_sleep_cmd = loginctl lock-session
    # after_sleep_cmd = hyprctl dispatch global quickshell:lockFocus
    after_sleep_cmd = $screen_on
    inhibit_sleep = 3
}

listener {
    timeout = 300 # 5mins
    on-timeout = loginctl lock-session
}

listener {
    timeout = 600 # 10mins
    on-timeout = $screen_off
    on-resume = $screen_on
}

# listener {
#     timeout = 900 # 15mins
#     on-timeout = $suspend_cmd
# }
